name = "cs263-project"
version = "0.1.0"
defaultTargets = ["cs263-project"]

[[lean_lib]]
name = "Cs263Project"

[[lean_exe]]
name = "cs263-project"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "8f9d9cff6bd728b17a24e163c9402775d9e6a365"